# practica supervivencia titanic

## cargando datos


In [2]:
import numpy as np
import pandas as pd
import sklearn 
import pickle

ruta = 'C:\\Users\\santi\\Downloads\\Data\\'

df =pd.read_csv (ruta+'titanic.xlsx - titanic.xls.csv')
df

Survived  Pclass                                               Name  \
0           0       3                             Mr. Owen Harris Braund   
1           1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2           1       3                              Miss. Laina Heikkinen   
3           1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4           0       3                            Mr. William Henry Allen   
..        ...     ...                                                ...   
882         0       2                               Rev. Juozas Montvila   
883         1       1                        Miss. Margaret Edith Graham   
884         0       3                     Miss. Catherine Helen Johnston   
885         1       1                               Mr. Karl Howell Behr   
886         0       3                                 Mr. Patrick Dooley   

        Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0      male  22.0                        1                        0     7.25  
1    female  38.0                        1                        0  712.833  
2    female  26.0                        0                        0    7.925  
3    female  35.0                        1                        0     53.1  
4      male  35.0                        0                        0    08.05  
..      ...   ...                      ...                      ...      ...  
882    male  27.0                        0                        0       13  
883  female  19.0                        0                        0       30  
884  female   7.0                        1                        2    23.45  
885    male  26.0                        0                        0       30  
886    male  32.0                        0                        0     7.75  

[887 rows x 8 columns]

## estudio de datos

In [3]:
df.head(5)

Survived  Pclass                                               Name  \
0         0       3                             Mr. Owen Harris Braund   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...   
2         1       3                              Miss. Laina Heikkinen   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle   
4         0       3                            Mr. William Henry Allen   

      Sex   Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0    male  22.0                        1                        0     7.25  
1  female  38.0                        1                        0  712.833  
2  female  26.0                        0                        0    7.925  
3  female  35.0                        1                        0     53.1  
4    male  35.0                        0                        0    08.05

In [4]:
df.describe()

Survived      Pclass         Age  Siblings/Spouses Aboard  \
count  887.000000  887.000000  887.000000               887.000000   
mean     0.385569    2.305524   29.471443                 0.525366   
std      0.487004    0.836662   14.121908                 1.104669   
min      0.000000    1.000000    0.420000                 0.000000   
25%      0.000000    2.000000   20.250000                 0.000000   
50%      0.000000    3.000000   28.000000                 0.000000   
75%      1.000000    3.000000   38.000000                 1.000000   
max      1.000000    3.000000   80.000000                 8.000000   

       Parents/Children Aboard  
count               887.000000  
mean                  0.383315  
std                   0.807466  
min                   0.000000  
25%                   0.000000  
50%                   0.000000  
75%                   0.000000  
max                   6.000000

## prepocesado


pasar de texto a numero la variable sexo

In [5]:
def f (x):
    if x== 'male':
        return 1
    else:
        return 0

df['Sex'] = df['Sex'].apply(f)

df.head(5)

Survived  Pclass                                               Name  Sex  \
0         0       3                             Mr. Owen Harris Braund    1   
1         1       1  Mrs. John Bradley (Florence Briggs Thayer) Cum...    0   
2         1       3                              Miss. Laina Heikkinen    0   
3         1       1        Mrs. Jacques Heath (Lily May Peel) Futrelle    0   
4         0       3                            Mr. William Henry Allen    1   

    Age  Siblings/Spouses Aboard  Parents/Children Aboard     Fare  
0  22.0                        1                        0     7.25  
1  38.0                        1                        0  712.833  
2  26.0                        0                        0    7.925  
3  35.0                        1                        0     53.1  
4  35.0                        0                        0    08.05

eliminar outliers de fare

In [6]:
df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce')
df=df[df['Fare']<200]
df=df.reset_index(drop=True)
df.describe()

Survived      Pclass         Sex         Age  \
count  762.000000  762.000000  762.000000  762.000000   
mean     0.346457    2.440945    0.666667   28.813215   
std      0.476153    0.758519    0.471714   13.568088   
min      0.000000    1.000000    0.000000    0.420000   
25%      0.000000    2.000000    0.000000   20.000000   
50%      0.000000    3.000000    1.000000   27.500000   
75%      1.000000    3.000000    1.000000   36.000000   
max      1.000000    3.000000    1.000000   80.000000   

       Siblings/Spouses Aboard  Parents/Children Aboard        Fare  
count               762.000000               762.000000  762.000000  
mean                  0.484252                 0.334646   27.656992  
std                   1.090101                 0.766981   36.764494  
min                   0.000000                 0.000000    0.000000  
25%                   0.000000                 0.000000    7.895800  
50%                   0.000000                 0.000000   12.587500  
75%                   1.000000                 0.000000   27.000000  
max                   8.000000                 6.000000  199.667000

In [7]:
X= df[['Sex','Age','Fare']].values
Y = df['Survived'].values  # Target variable
X

array([[ 1.   , 22.   ,  7.25 ],
       [ 0.   , 26.   ,  7.925],
       [ 0.   , 35.   , 53.1  ],
       ...,
       [ 0.   ,  7.   , 23.45 ],
       [ 1.   , 26.   , 30.   ],
       [ 1.   , 32.   ,  7.75 ]])

In [8]:
Y

array([0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,

## entrenamiento y testeo

In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test ,Y_train ,Y_test = train_test_split (X,Y,test_size=0.3)

## entrenamiento del modelo

In [10]:
from sklearn.linear_model import LogisticRegression

model=LogisticRegression()
model.fit (X_train,Y_train)

LogisticRegression()

mujer

In [11]:
print(model.predict([[0,5,100]]))

[1]


In [12]:
print(model.predict_proba([[0,5,100]]))

[[0.19495669 0.80504331]]


hombre

In [13]:
print(model.predict_proba([[1,45,1]]))

[[0.86018768 0.13981232]]


## probando el modelo

In [14]:
from sklearn.metrics import accuracy_score

y_predict=model.predict(X_test)
print (accuracy_score(y_predict,Y_test))

0.8122270742358079


In [15]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(y_predict,Y_test))

[[128  21]
 [ 22  58]]


## guardar modelo

In [16]:
pickle.dump (model,open ('mymodel.sav','wb'))
modelo_importado= pickle.load(open ('mymodel.sav','rb'))